### ISSUE TITLE
Can't select not to install boot loader (01.2016 beta / 02.2016 beta)

### ISSUE THREAD

**Issue by jonagoldman** [Apricity-OS/apricity-build#46]
I have a laptop running Windows 10 on internal SSD.
I want to connect an external 1TB HDD (USB 3) and install ApricityOs on it, using a 4GB Live Apricity OS USB Disk on Key.

The thing is **I don't want to add any boot loader to my main SSD**.
I want a super clean install only on the external HDD and manually enter the laptop boot menu and select the external drive when needed.

When I choose "Erase Disk, I can't select the boot loader:
![screenshot from 2016-02-25 17-19-06](https://cloud.githubusercontent.com/assets/1297559/13323850/0abe5954-dbe4-11e5-946f-bde4096fb322.png)

When I choose "Manual partitioning", the boot loader selection is disabled:
![screenshot from 2016-02-25 17-11-39](https://cloud.githubusercontent.com/assets/1297559/13323916/4189919c-dbe4-11e5-8843-2824926bed79.png)

In any case, I can't install Apricity OS without installing the boot loader.

Any help appreciated.

**Comment by Cyber-Logic** [comment]
Had the same issue.

You'll need to change your BIOS settings. Force it to only boot in Legacy mode, not UEFI.

Then boot from the Apricity OS Live CD. You should now see a WHITE boot screen instead of the previous black one. Boot from it. Now you'll be able to change the location of the bootloader installation.

**Comment by jonagoldman** [comment]
Thanks. Will try.

**Comment by lkhphuc** [comment]
@Cyber-Logic Thanks. Works perfectly.
