### ISSUE TITLE
Default web browser

### ISSUE THREAD

**Issue by itsgg** [Apricity-OS/apricity-build#98]
Can we change the fugly Google Chrome to Epiphany

**Comment by dealloc** [comment]
I'm personally very happy with Google Chrome

**Comment by Finnerale** [comment]
I would appreciate [Vivaldi](https://vivaldi.com) as the default web browser.
There is already a repo [`Herecura`](http://repo.herecura.eu/) which "fixes" the size of ffmpeg-codecs (in the AUR this package is more than 1GB big because it downloads the entire chromium source just to get the ffmpeg-codecs).
So we either add Vivaldi and the vivaldi-ffmpeg-codecs to the Apricity repo or we add Herecura which also provides tons of other packages that are not realy needed.

**Comment by dealloc** [comment]
What if we would have an option in the installer to choose some default such as your web browser from a set of popular choices (Chrome, Firefox, Vivaldi, Epiphany, ...)
I don't know how hard it would be to make something like this but I'm sure it'd resolve the issue of personal preference.

You can of course always just drop the package you don't like and install the one you do, it's not like you reinstall your OS every day (right?)
